name: Build, Analyze, and Scan

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Build and analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Scan filesystem with Trivy
        run: |
          # Install Trivy
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

          # Replace the following line with the command to scan your specific files or directories
          trivy fs .

        env:
          DOCKER_CLI_ACI: 1

      - name: Scan for OWASP Dependency-Check
        run: |
          # Install OWASP Dependency-Check 6.5.1
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.1/dependency-check-6.5.1-release.zip
          unzip dependency-check-6.5.1-release.zip

          # Run Dependency-Check on your project (replace with your project's build tool and options)
          ./dependency-check/bin/dependency-check.sh --scan ./ --disableYarnAudit --disableNodeAudit

        env:
          DOCKER_CLI_ACI: 1
    
      - name: Build Docker image
        run: |
          # Replace these commands with your actual Docker build commands
          docker build --build-arg TMDB_V3_API_KEY=ca86fe14eca3e76864bc17f59d319b92 -t netflix .
          docker tag netflix sevenajay/netflix:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push sevenajay/netflix:latest
        env:
          DOCKER_CLI_ACI: 1
     
